### ISSUE TITLE
[TODO] Ver9 - To be fixed for Release

### ISSUE THREAD

**Issue by alabamagan** [wuzhuobin/blood_vessel#51]
- [x] Need to fix #48 
- [x] MIP window would remain open if mainwindow closed
- [x] Re-link slot "About"
- [x] Need to fix #49

**Comment by alabamagan** [comment]
Fixed slot about 9e742c4 
Fixed MIP closing 4a56e59

**Comment by wuzhuobin** [comment]
#48 NOT able to fix currently
